export const REQUIRED_USERNAME = "Nhập tài khoản!"
export const REQUIRED_PASSWORD = "Nhập mật khẩu!"
export const REQUIRED_CONFIRMPASSWORD = "Mật khẩu không đúng!"
export const REQUIRED_FULLNAME = "Nhập họ và tên!"
export const REQUIRED_PHONENUMBER = "Nhập số điện thoại!"
export const REQUIRED_EMAIL = "Nhập email!"
export const REQUIRED_INDUSTRY = "Chọn ngành hàng!"
export const REQUIRED_SHOPNAME = "Nhập tên cửa hàng!"

export const REQUIRED_ADDRESSINFO = "Nhập địa chỉ!"
export const REQUIRED_PROVINCE = "Chọn tỉnh/thành!"
export const REQUIRED_DISTRICT = "Chọn quận/huyện!"
export const REQUIRED_WARD = "Chọn phường/xã!"

export const MIN_MAX = "Bạn phải nhập từ 4->16 ký tự!"

export const REQUIRED_PRODUCTNAME = "Nhập tên sản phẩm!"
export const REQUIRED_CATEGORY = "Chọn loại sản phẩm!"
export const REQUIRED_ORIGINALPRICE = "Nhập giá nhập hàng!"
export const REQUIRED_SALEPRICE = "Nhập giá bán hàng!"
export const REQUIRED_IMAGE = "Hãy chọn ảnh!"
export const REQUIRED_BRANCH = "Nhập thương hiệu"
export const REQUIRED_ORIGINCOUNTRY = "Nhập xuất xứ!"
export const REQUIRED_OTHERINFO = "Nhập thông tin mô tả cho sản phẩm!"
export const REQUIRED_STOCK = "Nhập số lượng cho sản phẩm!"